$schema: ./sample-schema.yaml
spring:
  profiles:
    active:
      - test

sample:
  boolean-sample: false
  string-sample: "config string"
  integer-sample: 10
  enum-sample: en2
  collection-sample:
    - test1
    - test2
    - test3
  map-sample:
    test1: test1value
    test2: test2value
  map-object-sample:
    item1:
      config-map1: abc
      config-map2: 1000
  config-sample-nested:
    nested-config1: nestedConfig
  deep-level1:
    deep-level2:
      list1:
        - id: abc
      list2:



logging:
  level:
    root: info
    sun:
      rmi: error
    javax:
      management: error

server:
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      cookie:
        partitioned: true










