spring:
  profiles:
    active: test

sample:
  deep-level1:
    deep-level2:
      list1:
        - id: 123

#  boolean-sample: false
#  string-sample: "config string"
#  integer-sample: 10
#  enum-sample: en2
#  collection-sample:
#    - test1
#    - test2
#    - test3
#  map-sample:
#    test1: test1value
#    test2: test2value
#
#  config-sample-nested:
#    nested-config1: nestedConfig
logging:
  level:
    root: debug
    sun:
      rmi: error
    javax:
      management: error
  file:
    name: test.log

json-config-schema:
  additional-exclude-classes:
    - "io.swagger.v3.oas.models.OpenAPI"








