= Spring Boot Config JSON Schema Generator
Alex Mondshain <alex.mondshaing@gmail.com>
2014-09-09
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]

A Spring Boot starter library that automatically generates JSON Schema documentation for your application's configuration properties. It simplifies the process of documenting and validating configuration by generating JSON Schema from your Spring Boot configuration classes.

[#introduction]
== Spring Boot Config JSON Schema Generator

A Spring Boot starter library uses spring context for @ConfigurationProperties and processes all relevant properties from spring boot own config metadata in class path spring-configuration-metadata.json to produce json schema that then can be used by compatible editors to edit and validate configuration outside of the java project project or validate configuration during ci

== Key Features

- Support for validation annotations and property constraints
- Compatible with Spring Boot 3.x
- Java 17+ runtime support
- REST API endpoint for schema access
- Unit test integration for schema generation

== Prerequisites

- Java 17 or higher
- Spring Boot 3.x
- Maven or Gradle build system
- To process project own properties following dependency should be included

[source,xml,subs=+attributes]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>
</dependency>
----

[#usage]
== Usage

=== Maven (use in unit tests)

Add the following dependency to your `pom.xml`:

[source,xml,subs=+attributes]
----
<dependency>
    <groupId>org.alexmond</groupId>
    <artifactId>spring-boot-config-json-schema-starter</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

.SampleJsonSchemaGeneratorTests.java
[source,java]
----
@SpringBootTest
@Slf4j
class SampleJsonSchemaGeneratorTests {

    @Autowired
    private JsonSchemaService jsonSchemaService;

    @Test
    void generateJsonSchema() throws Exception {

        String jsonConfigSchema;
        jsonConfigSchema = jsonSchemaService.generateFullSchema();

        ObjectMapper jsonMapper = new ObjectMapper();
        ObjectWriter jsonWriter = jsonMapper.writer(new DefaultPrettyPrinter());
        log.info("Writing json schema");
        jsonWriter.writeValue(Paths.get("sample-schema.json").toFile(),
            jsonMapper.readTree(jsonConfigSchema));

        ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());
        ObjectWriter yamlWriter = yamlMapper.writer(new DefaultPrettyPrinter());
        log.info("Writing yaml schema");
        yamlWriter.writeValue(Paths.get("sample-schema.yaml").toFile(),
            jsonMapper.readTree(jsonConfigSchema));
    }

}
----

=== Using as REST API Endpoint

To expose the JSON schema via a REST endpoint (similar to Swagger API docs), first add the following dependency to your `pom.xml`:

[source,xml,subs=+attributes]
----
<dependency>
    <groupId>org.alexmond</groupId>
    <artifactId>spring-boot-config-json-schema-starter</artifactId>
    <version>{project-version}</version>
</dependency>
----

.GenerateJsonSchema.java
[source,java]
----
@RestController
@Slf4j
public class GenerateJsonSchema {

    @Autowired
    private JsonSchemaService jsonSchemaService;

    @GetMapping("/config-schema")
    public String getConfigSchema() throws Exception {
        return jsonSchemaService.generateFullSchema();
    }

}
----

[#editors]
=== Using in editors


