$schema: ./sample-schema.json
spring:
  profiles:
    active:
      - test

sample:
  #  properties-example:
  #    abc : "test123"
  string-array-sample:
    - aaa
    - bbb
    - ccc
  boolean-sample: true
  string-sample: "config string"
  integer-sample: 10
  enum-sample: en2
  collection-sample:
    - test1
    - test2
    - test3
  map-sample:
    test1: test1value
    test2: test2value
  map-object-sample:
    item1:
      config-map1: abc
      config-map2: 1000
    item2:
      config-map1: abc
      config-map2: 1001


  config-sample-nested:
    nested-config1: nestedConfig




logging:
  level:
    root: info
    sun:
      rmi: error
    javax:
      management: error

server:
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      cookie:
        partitioned: true
---
$schema: ./sample-schema.json
spring:
  config:
    activate:
      on-profile:
        - test

sample:
  string-sample: "Test profile"
  deep-level1:
    deep-level2:
      list1:
        - id: abc
          param1: abd
          param2: zzz
      list2:
        - id: abc
          param2: bbbb
          param1: zzz
specialtype:
  url: "http://abc.com"
  uri: "http://abc.com"
  email: bzzz
  email-pattern: bzzz@yahoo.com
  inet4-address: 192.168.100.10
  uuid: AA97B177-9383-4934-8543-0F91A7A02836
  inet6-address: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"






