name: Java CI with Maven

on: [push, manual]
push:
  branches: [main]

checkout: true

jobs:
  build:
    image: maven:3.9-eclipse-temurin-17
    cache:
      key: m2-config-json-schema
      paths: [.m2/repository]
    steps:
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Pdefault --no-transfer-progress -Dmaven.repo.local=.m2/repository
      - name: Validate generated JSON schema sample
        run: |
          pip install --quiet check-jsonschema
          check-jsonschema --check-metaschema spring-boot-json-schema-sample/application.yaml
