name: Validate JSON Schemas

on: [ push, pull_request ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install check-jsonschema
        run: pipx install check-jsonschema
      - name: Validate files
        run: |
          check-jsonschema --schemafile https://json.schemastore.org/github-workflow.json .github/workflows/*.yml